version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: aws-scripts/stop_server.sh
      timeout: 180
  BeforeInstall:
    - location: aws-scripts/install_dependencies.sh
      timeout: 180
  ApplicationStart:
    - location: aws-scripts/start_server.sh
      timeout: 180
