version: 0.0
os: linux
files:
  source: /
  destination: /tmp/rails-app
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 180
